//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПМ._07_Соадминистрирование
{
    using System;
    using System.Collections.Generic;
    
    public partial class Оценки
    {
        public int Код { get; set; }
        public Nullable<long> Код_студента { get; set; }
        public Nullable<System.DateTime> Дата_экзамена { get; set; }
        public Nullable<long> Код_предмета { get; set; }
        public Nullable<byte> Оценка { get; set; }
    
        public virtual Предметы Предметы { get; set; }
        public virtual Студенты Студенты { get; set; }
    }
}
