//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПМ._07_Соадминистрирование
{
    using System;
    using System.Collections.Generic;
    
    public partial class Студенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Студенты()
        {
            this.Оценки = new HashSet<Оценки>();
        }
    
        public long Код_студента { get; set; }
        public string ФИО { get; set; }
        public string Пол { get; set; }
        public string Родители { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
        public string Пасспортные_данные { get; set; }
        public string Группа { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<System.DateTime> Дата_поступления { get; set; }
        public Nullable<bool> Очная_форма_поступления { get; set; }
        public Nullable<long> Номер_зачетки { get; set; }
        public Nullable<byte> Курс { get; set; }
        public Nullable<long> Код_специальности { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оценки> Оценки { get; set; }
        public virtual Специальности Специальности { get; set; }
    }
}
